language: java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - curl -OL https://github.com/oracle/oci-java-sdk/archive/v1.7.0.tar.gz
  - tar -xvf v1.7.0.tar.gz
  - pushd oci-java-sdk-1.7.0/ && mvn clean install && popd
script: mvn clean compile
